In [1]:
import torch
import numpy as np

# Creating Tensor

## From Python Array

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data.type())

torch.LongTensor


## From Numpy Array

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np.type())

torch.LongTensor


## Usefull creations

In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1362, 0.8613],
        [0.1735, 0.8487]]) 



In [ ]:
shape = (4,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")
print(f"Random Tensor: \n {rand_tensor} \n")


Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]) 

Random Tensor: 
 tensor([[0.2881, 0.0800],
        [0.6801, 0.0709],
        [0.9486, 0.8035],
        [0.5960, 0.7275]]) 



# Attributes of a Tensor

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors

## Send Tensor to GPU

In [3]:
tensor = torch.rand(3,4)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")


print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### Generic way to send tensor

In [ ]:
tensor = torch.rand(3,4)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


## Indexing tensor

In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensor

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.4275, 0.2503, 0.0970, 0.6682, 0.4275, 0.2503, 0.0970, 0.6682, 0.4275,
         0.2503, 0.0970, 0.6682],
        [0.9864, 0.4556, 0.4077, 0.3695, 0.9864, 0.4556, 0.4077, 0.3695, 0.9864,
         0.4556, 0.4077, 0.3695],
        [0.7406, 0.5597, 0.8842, 0.4621, 0.7406, 0.5597, 0.8842, 0.4621, 0.7406,
         0.5597, 0.8842, 0.4621]], device='cuda:0')


## Arithmetic Operations


In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Bridge with nupmy

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


If numpy array "n" is changed torch tensor "t" is also change becasue numpy and pytroch using same memory addreses. They are just projecting the same area to their data type.

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


# Convolution Operations on Tensors

In [5]:
import torch.nn as nn

https://github.com/vdumoulin/conv_arithmetic/blob/master/README.md

## Convolution animations

_N.B.: Blue maps are inputs, and cyan maps are outputs._

<table style="width:100%; table-layout:fixed;">
  <tr>
    <td><img width="150px" src=https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/no_padding_no_strides.gif?raw=true"></td>
    <td><img width="150px" src="https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/arbitrary_padding_no_strides.gif?raw=true"></td>
    <td><img width="150px" src="https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/same_padding_no_strides.gif?raw=true"></td>
    <td><img width="150px" src="https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/full_padding_no_strides.gif?raw=true"></td>
  </tr>
  <tr>
    <td>No padding, no strides</td>
    <td>Arbitrary padding, no strides</td>
    <td>Half padding, no strides</td>
    <td>Full padding, no strides</td>
  </tr>
  <tr>
    <td><img width="150px" src="https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/no_padding_strides.gif?raw=true"></td>
    <td><img width="150px" src="https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/padding_strides.gif?raw=true"></td>
    <td><img width="150px" src="https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/padding_strides_odd.gif?raw=true"></td>
    <td></td>
  </tr>
  <tr>
    <td>No padding, strides</td>
    <td>Padding, strides</td>
    <td>Padding, strides (odd)</td>
    <td></td>
  </tr>
</table>


Documentation of Conv2d function :

torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)

In [6]:
input_channel = 1 # for gray image input channel is 1 if it 3 channel colored image it will be 3
output_channel = 10 # desired output channel
kernel_size = 3 # 3 by 3 convulation filter
stride = 1
padding = 0
dilation = 1
conv = nn.Conv2d(input_channel, output_channel, kernel_size,stride,padding,dilation) # creating convulation filter

tensor = torch.ones(1,1,250,250) # creating tensor for demonstrate 1 channel gray image
output_tensor = conv(tensor) # convulate tensor with "conv" filter
print("Output shape of output tensor :",output_tensor.shape)

Output shape of output tensor : torch.Size([1, 10, 248, 248])


## Flatten Tensor and Fully Connected Neural Network

Documentation of Linear and Flatten function:

torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)

torch.nn.Flatten(start_dim=1, end_dim=-1)

In [7]:
tensor = torch.ones(1,1,250,250) # creating tensor for demonstrate 1 channel gray image
print("Shape of input tensor :",tensor.shape)
flatten = nn.Flatten()
features = flatten(tensor)
print("Flatten features size:",features.shape)

in_features = features.shape[-1]
out_features = 3200

fc1 = nn.Linear(in_features,out_features)
features = fc1(features)
print("After fully connected layer size:",features.shape)

relu = nn.ReLU()
output = relu(features)
print("After relu size:",output.shape)


Shape of input tensor : torch.Size([1, 1, 250, 250])
Flatten features size: torch.Size([1, 62500])
After fully connected layer size: torch.Size([1, 3200])
After relu size: torch.Size([1, 3200])


With nn.Sequential function modules can be stacked

In [ ]:
tensor = torch.ones(1,250,250) # creating tensor for demonstrate 1 channel gray image
flatten = nn.Flatten()
linear_relu_stack = nn.Sequential(
    nn.Linear(250*250, 512),
    nn.ReLU(),
    nn.Linear(512, 512),
    nn.ReLU(),
    nn.Linear(512, 10),
)

feautures = flatten(tensor)
output = linear_relu_stack(feautures)
print("After sequental layer size :",output.shape)
# output can be used for classification problem


After sequental layer size : torch.Size([1, 10])


# Creating Basic Model

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        # if input is 1x1x28x28
        self.conv_relu_stack = nn.Sequential(
            nn.Conv2d(1,16,5), # 1x16x24x24
            nn.ReLU(),
            nn.MaxPool2d(2), # 1x16x12x12
            nn.Conv2d(16,32,5,padding='valid'), # 1x32x8x8
            nn.ReLU(),
            nn.MaxPool2d(2) # 1x32x4x4

        )


        self.flatten = nn.Flatten() # feature size 32x4x4

        self.linear_relu_stack = nn.Sequential(
            nn.Linear(32*4*4, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10), # 10 output feature
        )

    def forward(self, x):
        x = self.conv_relu_stack(x)
        print(x.shape)
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

![img](https://miro.medium.com/v2/resize:fit:1400/1*uAeANQIOQPqWZnnuH-VEyw.jpeg)

In [ ]:
model = NeuralNetwork().to(device) # model created and send to the gpu

In [ ]:
tensor = torch.ones(1,1,28,28).to(device)
output = model(tensor)
print("Output Feature size is :",output.shape)

torch.Size([1, 32, 4, 4])
Output Feature size is : torch.Size([1, 10])
